{
 "title": "Żabka App Monitor",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "elasticsearch" },
   {
    "name": "filters",
    "query": "{\"find\": \"terms\", \"field\": \"SampleLabel.keyword\", \"query\": \"\"}"
   },
   {
    "name": "error",
    "query": "{\"find\": \"terms\", \"field\": \"ErrorCount\", \"query\": \"\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Global Error Rate",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "Timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "ErrorCount",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "SampleLabel.keyword:$filters",
     "timeField": "Timestamp"
    }
   ]
  },
  {
   "title": "Global Throughput",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "Timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "SampleCount",
       "id": "1",
       "inlineScript": "_value/10",
       "meta": {},
       "settings": { "script": { "inline": "_value/10" } },
       "type": "sum"
      }
     ],
     "query": "SampleLabel.keyword:$filters",
     "timeField": "Timestamp"
    }
   ]
  },
  {
   "title": "# errors",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "Timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "ErrorCount",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "SampleLabel.keyword:$filters",
     "timeField": "Timestamp"
    }
   ]
  },
  {
   "title": "# threads vs response time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ms", "label": "response time" }
   ],
   "targets": [
    {
     "alias": "# Threads",
     "bucketAggs": [
      { "field": "Timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "AllThreads",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "SampleLabel.keyword:$filters && ErrorCount:$error",
     "timeField": "Timestamp"
    },
    {
     "bucketAggs": [
      { "field": "Timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "ResponseTime",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "ResponseTime",
       "id": "3",
       "meta": {},
       "settings": {
        "percents": [
         "75",
         "90"
        ]
       },
       "type": "percentiles"
      },
      {
       "field": "ResponseTime",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "SampleLabel.keyword:$filters && ErrorCount:$error",
     "timeField": "Timestamp"
    }
   ]
  },
  {
   "title": "ResponseTime Graph",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "SampleLabel.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "5" },
       "type": "terms"
      },
      { "field": "SampleStartTime", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "ResponseTime",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "ResponseTime:* and SampleLabel.keyword:$filters and ErrorCount:$error",
     "timeField": "SampleStartTime"
    }
   ]
  },
  {
   "title": "Hits and error",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "#" }
   ],
   "targets": [
    {
     "alias": "Global Throughput",
     "bucketAggs": [
      { "field": "Timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "SampleCount",
       "id": "4",
       "inlineScript": "_value/10",
       "meta": {},
       "settings": { "script": { "inline": "_value/10" } },
       "type": "sum"
      }
     ],
     "query": "SampleLabel.keyword:$filters",
     "timeField": "Timestamp"
    },
    {
     "alias": "Throughput {{SampleLabel.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "SampleLabel.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "Timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "SampleCount",
       "id": "1",
       "inlineScript": "_value/10",
       "meta": {},
       "settings": { "script": { "inline": "_value/10" } },
       "type": "sum"
      }
     ],
     "query": "SampleLabel.keyword:$filters",
     "timeField": "Timestamp"
    },
    {
     "alias": "# Global Error",
     "bucketAggs": [
      { "field": "Timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "ErrorCount",
       "id": "1",
       "inlineScript": "_value/10*-1",
       "meta": {},
       "settings": { "script": { "inline": "_value/10*-1" } },
       "type": "sum"
      }
     ],
     "query": "SampleLabel.keyword:$filters",
     "timeField": "Timestamp"
    },
    {
     "alias": "# Errors {{SampleLabel.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "SampleLabel.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "Timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "ErrorCount",
       "id": "1",
       "inlineScript": "_value/10*-1",
       "meta": {},
       "settings": { "script": { "inline": "_value/10*-1" } },
       "type": "sum"
      }
     ],
     "query": "SampleLabel.keyword:$filters",
     "timeField": "Timestamp"
    }
   ]
  },
  {
   "title": "Bytes Sent and Received",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Global Sent",
     "bucketAggs": [
      { "field": "Timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "SentBytes",
       "id": "1",
       "inlineScript": "_value/10*-1",
       "meta": {},
       "settings": { "script": { "inline": "_value/10*-1" } },
       "type": "sum"
      }
     ],
     "query": "SampleLabel.keyword:$filters && ErrorCount:$error",
     "timeField": "Timestamp"
    },
    {
     "alias": "Sent {{SampleLabel.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "SampleLabel.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "Timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "SentBytes",
       "id": "1",
       "inlineScript": "_value*-1/10",
       "meta": {},
       "settings": { "script": { "inline": "_value*-1/10" } },
       "type": "sum"
      }
     ],
     "query": "SampleLabel.keyword:$filters && ErrorCount:$error",
     "timeField": "Timestamp"
    },
    {
     "alias": "Global Received",
     "bucketAggs": [
      { "field": "Timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "Bytes",
       "id": "1",
       "inlineScript": "_value/10",
       "meta": {},
       "settings": { "script": { "inline": "_value/10" } },
       "type": "sum"
      }
     ],
     "query": "SampleLabel.keyword:$filters && ErrorCount:$error",
     "timeField": "Timestamp"
    },
    {
     "alias": "Received {{SampleLabel.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "SampleLabel.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "Timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "Bytes",
       "id": "1",
       "inlineScript": "_value/10",
       "meta": {},
       "settings": { "script": { "inline": "_value/10" } },
       "type": "sum"
      }
     ],
     "query": "SampleLabel.keyword:$filters && ErrorCount:$error",
     "timeField": "Timestamp"
    }
   ]
  },
  {
   "title": "Synthesis Report",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "SampleLabel.keyword",
       "id": "6",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "8", "type": "count" },
      {
       "field": "ResponseTime",
       "id": "9",
       "meta": {},
       "settings": {},
       "type": "min"
      },
      {
       "field": "ResponseTime",
       "id": "10",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "ResponseTime",
       "id": "11",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "Bytes",
       "id": "12",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "SentBytes",
       "id": "13",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "ErrorCount",
       "id": "14",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "Latency",
       "id": "15",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "ResponseTime",
       "id": "16",
       "meta": {},
       "settings": {
        "percents": [
         "90",
         "95",
         "99"
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "SampleLabel.keyword:$filters && ErrorCount:$error",
     "timeField": "Timestamp"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_document"
      }
     ],
     "query": "SampleLabel.keyword:$filters && ErrorCount:1",
     "timeField": "Timestamp"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "ms", "label": "response time" }
   ],
   "targets": [
    {
     "alias": "{{metric}} {{SampleLabel.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "SampleLabel.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "5" },
       "type": "terms"
      },
      { "field": "SampleStartTime", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "ResponseTime",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "ResponseTime",
       "hide": true,
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "ResponseTime",
       "hide": true,
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "min"
      },
      {
       "field": "ResponseTime",
       "hide": true,
       "id": "6",
       "meta": {},
       "settings": { "percents": [ "90" ] },
       "type": "percentiles"
      }
     ],
     "query": "SampleLabel.keyword:$filters && ErrorCount:$error",
     "timeField": "SampleStartTime"
    }
   ]
  }
 ]
}